preguntas = {
  "REALISTIC": [
    "¿Eres práctico y disfrutas de actividades prácticas como arreglar cosas o trabajar con herramientas?",
    "¿Prefieres actividades al aire libre que implican movimiento físico y estar activo?",
    "¿Te interesa entender cómo funcionan los sistemas mecánicos o leer planos técnicos?",
    "¿Encuentras satisfacción en resolver problemas prácticos utilizando métodos lógicos?",
    "¿Te gustaría una carrera que te permita construir u crear objetos físicos?",
    "¿Te atraen las carreras que involucran trabajar en entornos naturales o con animales?",
    "¿Tienes habilidad para solucionar problemas mecánicos o eléctricos?",
    "¿Eres alguien que disfruta jugar deportes o participar en actividades atléticas?",
    "¿Te gusta trabajar de manera independiente en proyectos que requieren habilidades prácticas?",
    "¿Eres hábil utilizando herramientas y maquinaria para crear o reparar cosas?"
  ],
  "INVESTIGATIVE": [
    "¿Eres curioso sobre cómo funcionan las cosas o por qué ocurren ciertos fenómenos en el mundo natural?",
    "¿Disfrutas analizando datos y encontrando patrones o tendencias?",
    "¿Tienes habilidad para resolver problemas complejos utilizando razonamiento analítico?",
    "¿Te gustaría conducir experimentos o investigaciones para descubrir nueva información?",
    "¿Te interesa entender teorías y principios científicos?",
    "¿Disfrutas trabajando con computadoras para analizar datos o simular escenarios?",
    "¿Eres alguien que lee revistas científicas o técnicas para mantenerte informado?",
    "¿Prefieres trabajar de manera independiente para explorar nuevas ideas o conceptos?",
    "¿Eres bueno observando detalles y notando cambios en tu entorno?",
    "¿Te gustaría una carrera que te desafíe a pensar críticamente y resolver problemas intelectuales?"
  ],
  "ARTISTIC": [
    "¿Eres alguien que disfruta expresándote a través de medios creativos como dibujar o pintar?",
    "¿Encuentras placer en asistir a eventos artísticos como conciertos, teatros o exposiciones de arte?",
    "¿Eres imaginativo y disfrutas explorando nuevas ideas o perspectivas a través del arte?",
    "¿Te gusta escribir historias, poesía o música como una forma de expresar tus pensamientos?",
    "¿Eres intuitivo y a menudo confías en tus instintos o sentimientos en los proyectos creativos?",
    "¿Te gustaría diseñar o decorar espacios para crear ambientes visualmente atractivos?",
    "¿Encuentras satisfacción en tomar fotografías o capturar momentos a través del arte visual?",
    "¿Eres alguien que disfruta trabajando en proyectos de manualidades o bricolaje en tu tiempo libre?",
    "¿Prefieres carreras que te permitan trabajar de manera independiente e innovar creativamente?",
    "¿Te atraen las carreras que involucran expresar tu individualidad y visión artística?"
  ],
  "SOCIAL": [
    "¿Eres naturalmente amigable y disfrutas interactuar con una amplia gama de personas?",
    "¿Encuentras satisfacción en ayudar a otros a resolver problemas personales o sociales?",
    "¿Tienes habilidad para liderar discusiones grupales o actividades para lograr objetivos comunes?",
    "¿Disfrutas ofreciendo tu tiempo como voluntario para apoyar causas comunitarias o humanitarias?",
    "¿Eres empático y capaz de entender y mediar en conflictos entre otros?",
    "¿Te gustaría una carrera que involucre mentoría o enseñanza a otros en entornos grupales?",
    "¿Prefieres trabajar en equipos donde la colaboración y la comunicación son fundamentales?",
    "¿Eres alguien que disfruta planificando y organizando eventos sociales o actividades?",
    "¿Tienes pasión por trabajar con jóvenes o ayudar a que desarrollen habilidades?",
    "¿Te interesan las carreras que te permitan tener un impacto positivo en la sociedad o las comunidades?"
  ],
  "ENTERPRISING": [
    "¿Eres seguro de ti mismo y disfrutas tomar la iniciativa para comenzar nuevos proyectos o empresas?",
    "¿Tienes una personalidad persuasiva y disfrutas convencer a otros para que apoyen tus ideas?",
    "¿Eres sociable y te sientes cómodo haciendo redes con personas de diversos orígenes?",
    "¿Encuentras satisfacción organizando y liderando eventos o actividades?",
    "¿Eres entusiasta en tomar decisiones que puedan influenciar a otros o lograr objetivos?",
    "¿Te gustaría una carrera que involucre vender productos o promover ideas innovadoras?",
    "¿Disfrutas dando presentaciones o discursos para persuadir a otros de tu punto de vista?",
    "¿Eres energético y prosperas en entornos que requieren liderazgo dinámico?",
    "¿Eres asertivo y capaz de negociar efectivamente para lograr resultados deseados?",
    "¿Aspiras a comenzar tu propio negocio o liderar un equipo hacia el éxito?"
  ],
  "CONVENTIONAL": [
    "¿Prefieres trabajar en entornos estructurados con procedimientos claramente definidos?",
    "¿Encuentras satisfacción en mantener registros precisos o manejar información detallada?",
    "¿Eres metódico y eficiente al completar tareas que requieren atención a los detalles?",
    "¿Disfrutas usando tecnología o equipos de procesamiento de datos para organizar información?",
    "¿Tienes habilidad para seguir instrucciones y cumplir con protocolos establecidos?",
    "¿Te gustaría una carrera que involucre trabajar con números o realizar cálculos financieros?",
    "¿Eres consciente y confiable cuando se trata de manejar tareas administrativas?",
    "¿Prefieres roles que requieran que trabajes dentro de sistemas o marcos establecidos?",
    "¿Eres bueno en multitareas y manejar múltiples responsabilidades simultáneamente?",
    "¿Destacas en roles que implican realizar tareas rutinarias o papeleo eficientemente?"
  ]
}

career_data = {
    "Contador": ["Conventional", "Investigative", "Enterprising"],
    "Arquitecto": ["Artistic", "Investigative", "Realistic"],
    "Ingeniero Civil": ["Realistic", "Investigative", "Conventional"],
    "Programador": ["Investigative", "Realistic", "Conventional"],
    "Psicólogo": ["Social", "Artistic", "Investigative"],
    "Enfermero": ["Social", "Realistic", "Investigative"],
    "Diseñador Gráfico": ["Artistic", "Enterprising", "Realistic"],
    "Profesor": ["Social", "Enterprising", "Conventional"],
    "Biólogo": ["Investigative", "Realistic", "Artistic"],
    "Abogado": ["Enterprising", "Social", "Investigative"],
    "Farmacéutico": ["Investigative", "Conventional", "Social"],
    "Chef": ["Artistic", "Realistic", "Enterprising"],
    "Electricista": ["Realistic", "Conventional", "Investigative"],
    "Mecánico": ["Realistic", "Investigative", "Conventional"],
    "Terapeuta Físico": ["Social", "Investigative", "Realistic"],
    "Administrativo": ["Conventional", "Enterprising", "Realistic"],
    "Piloto": ["Realistic", "Enterprising", "Investigative"],
    "Fotógrafo": ["Artistic", "Enterprising", "Realistic"],
    "Gerente de Ventas": ["Enterprising", "Social", "Conventional"],
    "Químico": ["Investigative", "Realistic", "Conventional"],
    "Analista de Sistemas": ["Investigative", "Conventional", "Realistic"],
    "Veterinario": ["Investigative", "Social", "Realistic"],
    "Fisioterapeuta": ["Social", "Investigative", "Realistic"],
    "Trabajador Social": ["Social", "Enterprising", "Conventional"],
    "Bibliotecario": ["Conventional", "Investigative", "Social"],
    "Actor": ["Artistic", "Enterprising", "Realistic"],
    "Contador Público": ["Conventional", "Investigative", "Enterprising"],
    "Dentista": ["Investigative", "Social", "Realistic"],
    "Astrónomo": ["Investigative", "Realistic", "Artistic"],
    "Periodista": ["Artistic", "Investigative", "Enterprising"]
}
